### ISSUE TITLE
Tag a packer 0.10.1 release

### ISSUE THREAD

**Issue by gtaylor** [hashicorp/docker-hub-images#10]
Looks like there's a 0.10.0 tag, but not 0.10.1: https://hub.docker.com/r/hashicorp/packer/tags/

We're running packer in CI and don't want to auto-upgrade using latest.

**Comment by dustyburwell** [comment]
Same story, but for 0.11.0

**Comment by SwampDragons** [comment]
Closing this because all of the latest releases have been tagged.
