### ISSUE TITLE
Terraform Get Doesn't work with Git SSH

### ISSUE THREAD

**Issue by nickm4062** [hashicorp/docker-hub-images#17]
git and ssh are missing from the image so module references that use git::ssh do not work.

git is in the full image but ssh is not

Suggest removing the line   apk del git and adding openssh to the add update

**Comment by yamaszone** [comment]
This issue is [addressed](https://github.com/hashicorp/docker-hub-images/pull/26). You may want to download latest hashicorp/terraform:light.

**Comment by nickm4062** [comment]
@yamaszone it is still missing ssh

**Comment by catsby** [comment]
@nickm4062 can you give us some example output of the command you're running, and the error(s) you're receiving?

**Comment by nickm4062** [comment]
docker pull hashicorp/terraform:light
light: Pulling from hashicorp/terraform

3690ec4760f9: Already exists
eba890c32e0e: Pull complete
Digest: sha256:0f34923c04916ce0f149f15f61c14da8d9d555084c85d4607c78d3eb0894ba3c
Status: Downloaded newer image for hashicorp/terraform:light

docker run  -e AWS_SHARED_CREDENTIALS_FILE="/root/.aws/credentials" -e AWS_PROFILE=saml -i -t --rm -w /local -v $HOME/.aws:/root/.aws -v $PWD:/local -v $HOME/.ssh:/root/.ssh/   hashicorp/terraform:light get --update
Get: git::ssh://GITREPO (update)
Error loading Terraform: Error downloading modules: error downloading 'ssh://GITREPO': /usr/bin/git exited with 1: error: cannot run ssh: No such file or directory
fatal: unable to fork

Locally I have tested 

FROM hashicorp/terraform:latest
RUN apk add --update git openssh

which seems to make it work

**Comment by nickm4062** [comment]
I removed our github enterprise urls for internal security reasons
