### ISSUE TITLE
Packer updated to use govendor, this image wasn't

### ISSUE THREAD

**Issue by usererror** [hashicorp/docker-hub-images#20]
Packer was updated recently (~18hrs ago at time of writing) to use govendor instead of godeps (https://github.com/mitchellh/packer/commit/02029503870181b139dee74faa4e270b6e32f5e1) and the image build is probably failing due to this -- it looks like the tracking info on the README is broken right now.

Adding these two lines fixed our personal Dockerfile which uses similar commands for installing packer:
`RUN go get github.com/kardianos/govendor`
… <workdir cmd>
`RUN govendor fetch packer`

**Comment by mwhooker** [comment]
thanks so much for catching this. I'm still learning all the packer touch points. will get this fixed asap
