### ISSUE TITLE
hashicorp/terraform:full contains the wrong version

### ISSUE THREAD

**Issue by johanneswuerbach** [hashicorp/docker-hub-images#28]
When looking at https://github.com/hashicorp/docker-hub-images/blob/master/terraform/Dockerfile-full, I expected to find terraform version 0.7.13 inside the container, but it looks like `Terraform v0.8.0-dev (e90b70ee13aa1be07cf66ae4b3b337b067ababfa)` is included. Is this expected?

```
$ docker pull hashicorp/terraform:full && docker run hashicorp/terraform:full version
full: Pulling from hashicorp/terraform
Digest: sha256:eb8ab38e16fed207a7bb0df3dd379cf7613964eda324d7408c36775df04e2c8e
Status: Image is up to date for hashicorp/terraform:full
Terraform v0.8.0-dev (e90b70ee13aa1be07cf66ae4b3b337b067ababfa)

```

As a side note: Would it be possible to get tagged versions of the full image? I found it incredible useful for building terraform with some custom plugins for internal usage.

**Comment by catsby** [comment]
Sorry for the trouble here! This has been patched with the latest release of v0.8
