### ISSUE TITLE
Packer light build failing on Docker Hub

### ISSUE THREAD

**Issue by shanonvl** [hashicorp/docker-hub-images#38]
Packer light builds have been [failing on Docker Hub for ~2 weeks](https://hub.docker.com/r/hashicorp/packer/builds/):
![image](https://user-images.githubusercontent.com/2326578/27394148-2b87d5be-5679-11e7-9c52-027fc1ed7596.png)

I've investigated a bit and the build fails during this step:
```
RUN sed -i '/packer_${PACKER_VERSION}_linux_amd64.zip/!d' packer_${PACKER_VERSION}_SHA256SUMS
```
with the following error:
```
sha256sum: packer_1.0.1_SHA256SUMS: no checksum lines found
```

This appears to be due to the single quotes; the `${PACKER_VERSION}` is not replaced.

**Comment by SwampDragons** [comment]
This appears to have been fixed, so I'm closing. Apologies for the long delay with no response.
