### ISSUE TITLE
Missing hashicorp/terrafom docker image tags

### ISSUE THREAD

**Issue by rvandegrift** [hashicorp/docker-hub-images#41]
https://hub.docker.com/r/hashicorp/terraform/tags/ - looks like tags for 0.9.10 and 0.9.11 are missing.  Are these tags pushed automatically on release?

**Comment by jhvhs** [comment]
0.9.10 is there (latest), but 0.9.11 is not, and terraform does not run at all:
```
docker run -i -t \
[... terraform options skipped ...]
Terraform v0.9.10

Your version of Terraform is out of date! The latest version
is 0.9.11. You can update by downloading from www.terraform.io
```

What is the point of keeping outdated versions of the docker image?
Terraform seems to prevent old versions from running anyway:
https://github.com/hashicorp/terraform/blob/1f1f898695e1c413786710de866a482ec1f4a045/command/version.go#L65-L69

**Comment by elblivion** [comment]
+1 - 0.9.10 had a bug and we have some states that cannot be downgraded from that version, could you PTAL at pushing 0.9.11?

**Comment by muconsulting** [comment]
Any update ? still missing the tag 0.9.11 in docker hub

**Comment by willejs** [comment]
@catsby can you release the merged changes please?

**Comment by SmoshySmosh** [comment]
Can we get some traction on this?

**Comment by drubin** [comment]
Seems relevant #51

**Comment by paultyng** [comment]
We no longer build Terraform docker images from this repository (Packer images are built here still).

Issues and pull requests on the Terraform docker image should be opened on the main Terraform repository: https://github.com/hashicorp/terraform
