### ISSUE TITLE
Unable to run `init` fo project

### ISSUE THREAD

**Issue by toby-griffiths** [hashicorp/docker-hub-images#47]
Hi there,
I'm new to Terraform & have tried running a simple `init` command as follows…

    $ docker run --rm -v $PWD:/data --workdir=/data hashicorp/terraform:light init

… but I get the error

```
Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

Error installing provider "aws": Get https://releases.hashicorp.com/terraform-provider-aws/: proxyconnect tcp: dial tcp 192.168.65.1:62123: getsockopt: connection refused.
```

I've also tried running it on the host network…

    $ docker run --rm -v $PWD:/data --workdir=/data --network host hashicorp/terraform:light init

… but that didn't work either.  Any ideas why not?

**Comment by benfortuna** [comment]
I have a similar problem, not sure if it's the same issue. 

If I run AWS CLI directly in (a customised) container it works, but using Terraform with an AWS provider results in proxyconnect error.

```
$ docker run --rm -it -v $PWD:/data --volume "$HOME/.aws:/root/.aws" -e AWS_PROFILE=sample -e http_proxy=${http_proxy:-} --workdir=/data --network host hashicorp/terraform:light plan
Failed to load backend:
Error configuring the backend "s3": RequestError: send request failed
caused by: Post https://sts.amazonaws.com/: proxyconnect tcp: dial tcp 10.xx.xx.108:3128: connect: connection refused

Please update the configuration in your Terraform files to fix this error.
If you'd like to update the configuration interactively without storing
the values in your configuration, run "terraform init".
```

**Comment by benfortuna** [comment]
In fact I've just solved my problem.

This works:

```
http_proxy=http://127.0.0.1:3128/
https_proxy=http://127.0.0.1:3128/
```

this doesn't:

```
http_proxy=http://localhost:3128/
https_proxy=http://localhost:3128/
```

Not sure if there's a difference in how Terraform resolves localhost in Docker containers, for now I'll use the local loopback address.

**Comment by paultyng** [comment]
We no longer build Terraform docker images from this repository (Packer images are built here still).

Issues and pull requests on the Terraform docker image should be opened on the main Terraform repository: https://github.com/hashicorp/terraform
