### ISSUE TITLE
Broken ImageLayers link and automated docker Builds

### ISSUE THREAD

**Issue by drubin** [hashicorp/docker-hub-images#51]
It seems like the docker images on docker-hub are no longer built from CI? The last build was 4 months ago.  (Versions are manually pushed?)

https://hub.docker.com/r/hashicorp/terraform/ 
https://hub.docker.com/r/hashicorp/terraform/builds/ 

This introduces some trust issues regarding the images that are being pushed to docker-hub vs the source code within the `terraform` folder. 

The following [DockerFile](https://github.com/hashicorp/docker-hub-images/blob/master/terraform/Dockerfile-light) still lists 0.10.0 as the latest version but there are builds for 0.11.* 

Is this repo still even used? Are these docker images built from CI if so are they public?

This is also the issue that broke the layering in the ReadMe's 

https://imagelayers.io/?images=hashicorp%2Fterraform:0.6.14 
vs
https://imagelayers.io/?images=hashicorp%2Fterraform:latest 

It seems like the last build for latest was automated. https://hub.docker.com/r/hashicorp/terraform/builds/bnfcu6rpkrae2iuzvzbbyrl/

I suspect any merge to this repository will result in downgrading `hashicorp/terraform:latest` from the current 0.11.1 version to the current 0.10 in the git repo depending if there are still automated builds setup.

**Comment by drubin** [comment]
@slackpad Do you still maintain/work on the docker images?

Seems like this is relevant #11 

If this repo is not the source of the docker images maybe you should close it?

**Comment by tmshn** [comment]
The source of the Terraform's official image seem to be located here since https://github.com/hashicorp/terraform/pull/15596
https://github.com/hashicorp/terraform/blob/v0.11.7/Dockerfile

**Comment by paultyng** [comment]
We no longer build Terraform docker images from this repository (Packer images are built here still).

Issues and pull requests on the Terraform docker image should be opened on the main Terraform repository: https://github.com/hashicorp/terraform
