### ISSUE TITLE
packer examples

### ISSUE THREAD

**Issue by lindsm** [hashicorp/docker-hub-images#53]
I have packer running locally.  Seemed to be a not friendly, non scaleable, and non repeatable setup.  Saw a docker image with packer, thought I would check it out.  Sounds like it would solve all the things I was talking about if I could just spin up packer in a docker container and have it work. It is very unclear how to use it though.  Looking through the commits, I see that we added terraform examples for https://github.com/hashicorp/docker-hub-images/issues/8.

I start poking around, trying out various things with the packer image; docker run -v /Users/user1/Documents/Projects/packer_base:/data hashicorp/packer:light build -on-error=ask -force -only CentOS7-VBOX /data/packer_templates/centos7/test7.json. Could not find VBoxManage.  Tried the hashicorp/packer:full, same story.  Messed around with entry point, and poked around the alpine build a little, 100% correct, no VBoxManage! :)

I do not see packer examples. Is my use case the proper way to be using the packer image? I'm guessing not by my repeated failures!

**Comment by munntjlx** [comment]
I want to use a custom json file. Do I have to bake into the docker image? What is the 'proper' way for importing config?

**Comment by SwampDragons** [comment]
Does the example here not work for you? https://hub.docker.com/r/hashicorp/packer/

further example for using packer build: 

```docker run -i -t hashicorp/packer:light build myfile.json```

**Comment by SwampDragons** [comment]
I've updated the README with an example of how to run a build while using a mounted folder
