### ISSUE TITLE
Terraform remote state version is greater than Docker image version

### ISSUE THREAD

**Issue by adjavaherian** [hashicorp/docker-hub-images#57]
It seems as if the last few CI builds that we've done here, are bumping the remote state (s3) to 

```
    "version": 3,
    "terraform_version": "0.11.7",
```

after a successful plan / apply

This is a little strange, because when I login to the container (terraform:light) directly, and create a local, minimal state with an AWS module, I see

```
    "version": 3,
    "terraform_version": "0.11.5",
```

The result is that subsequent builds cannot be applied 

```
Terraform doesn't allow running any operations against a state
deploy_1  | that was written by a future Terraform version. The state is
deploy_1  | reporting it is written by Terraform '0.11.7'
```

If I manually edit the remote state file, I can build again, but it will continue to bump it back up to latest.  Am I doing something that would upgrade the stack, somewhere between plan and apply?

Thanks.

**Comment by paultyng** [comment]
We no longer build Terraform docker images from this repository (Packer images are built here still).

Issues and pull requests on the Terraform docker image should be opened on the main Terraform repository: https://github.com/hashicorp/terraform
