### ISSUE TITLE
The Terraform example at DockerHub is outdated

### ISSUE THREAD

**Issue by TG9541** [hashicorp/docker-hub-images#58]
**Problem:**

The example usage at https://hub.docker.com/r/hashicorp/terraform/ is outdated, which is likely to frustrate beginners.

**How to reproduce it:**
Using `docker run -i -t hashicorp/terraform:light plan main.tf`  results in sessions like following:

```
thomas@w500:~/source/terraform$ ls -l
total 8
-rw-rw-r-- 1 thomas thomas 2331 Jun  3 10:12 account.json
-rw-rw-r-- 1 thomas thomas  937 Jun  3 10:14 main.tf
thomas@w500:~/source/terraform$ docker run -it hashicorp/terraform:light version
Terraform v0.11.7

thomas@w500:~/source/terraform$ docker run -it hashicorp/terraform:light plan main.tf
Failed to load Terraform configuration or plan: open main.tf: no such file or directory
```
The solution is to follow the examples in the [GitHub README.md](https://github.com/hashicorp/docker-hub-images/tree/master/terraform).

**Proposed solution:**
Please edit the docs at DockerHub, remove the broken example, and point to the up-to-date docs at GitHub instead.

**Comment by christhomas** [comment]
Why is this not fixed yet? It seems like a very easy to solve problem?

**Comment by deenski** [comment]
![image](https://user-images.githubusercontent.com/18223276/48085328-27ee6600-e1b7-11e8-9f9d-90d8c6628ec2.png)

Same.. Bump.

**Comment by deenski** [comment]
![image](https://user-images.githubusercontent.com/18223276/48085578-e7431c80-e1b7-11e8-9f28-8e5e9ee1ca0b.png)
Same. Bump.

**Comment by paultyng** [comment]
We no longer build Terraform docker images from this repository (Packer images are built here still).

Issues and pull requests on the Terraform docker image should be opened on the main Terraform repository: https://github.com/hashicorp/terraform

**Comment by Curtis017** [comment]
@TG9541 that `README.md` link is broken. Could you please provide the solution in this thread. I would like to use the docker image to run plans. 😄

**Comment by deenski** [comment]
@TG9541 Solution: https://github.com/hashicorp/terraform#docker

**Comment by jasong1978** [comment]
Where is the newly supported docker image?

**Comment by wedneyyuri** [comment]
**Solution:** mount the volume and overwrite the working directory. Example:

```
docker run -it -v $(pwd):/workpace -w /workpace hashicorp/terraform:0.12.2 apply
```
