### ISSUE TITLE
Error checking configuration: configuration path must be a directory

### ISSUE THREAD

**Issue by red8888** [hashicorp/docker-hub-images#59]
Not sure what I'm doing wrong:
`docker run --rm -v $(pwd):/app/ -w /app/ hashicorp/terraform:light init my.tf`

Error checking configuration: configuration path must be a directory: my.tf

**Comment by ThomasVdBerge** [comment]
the init command does not require a file. So you can just run it like this:

`docker run --rm -v $(pwd):/app/ -w /app/ hashicorp/terraform:light init`

**Comment by paultyng** [comment]
We no longer build Terraform docker images from this repository (Packer images are built here still).

Issues and pull requests on the Terraform docker image should be opened on the main Terraform repository: https://github.com/hashicorp/terraform
