### ISSUE TITLE
Improve documentation, aka How to run?

### ISSUE THREAD

**Issue by loxal** [hashicorp/docker-hub-images#61]
Sorry but reading https://hub.docker.com/r/hashicorp/terraform/ I have no idea how to use Terraform as a docker container. 

alex@sun:~/some-path$ docker run -i -t hashicorp/terraform:light plan

Error: No configuration files found!

Plan requires configuration to be present. Planning without a configuration
would mark everything for destruction, which is normally not what is desired.
If you would like to destroy everything, please run plan with the "-destroy"
flag or create a single empty configuration file. Otherwise, please create
a Terraform configuration file in the path being executed and try again.

I would rather expect the same output as with `terraform plan`...? So something is missing?

**Comment by ThomasVdBerge** [comment]
See https://github.com/hashicorp/docker-hub-images/issues/58

**Comment by paultyng** [comment]
We no longer build Terraform docker images from this repository (Packer images are built here still).

Issues and pull requests on the Terraform docker image should be opened on the main Terraform repository: https://github.com/hashicorp/terraform
