### ISSUE TITLE
request for versioned full images

### ISSUE THREAD

**Issue by jeff-knurek** [hashicorp/docker-hub-images#62]
currently the docker tags that are available include:
* latest
* full
* light
* 0.11.8
* 0.11.7
* .....

where `0.11.8` maps to the `light` version of the image. 

----
In order to be able to make use of the `full` image and still keep versioning, I propose adding: `full-0.11.8` _(or comparable)_

**Comment by SwampDragons** [comment]
Thanks for opening this issue, and apologies for the long delay. This has been implemented for v1.5.2
