### ISSUE TITLE
Packer Docker Hub builds broken

### ISSUE THREAD

**Issue by danports** [hashicorp/docker-hub-images#69]
Hi guys, it looks like your Docker Hub builds have been failing for a month or so?

https://hub.docker.com/r/hashicorp/packer/builds/

**Comment by bengaywins** [comment]
@catsby is there anyone that can work on this? The builds have been failing for over 3 months. The most recent successful build is 1.3.1 while the most recent version of packer is 1.3.4 released a week ago.

**Comment by bengaywins** [comment]
Here's the error for the main Dockerfile

```+ exec go get -v -d
can't load package: package app: no buildable Go source files in /go/src/app
The command '/bin/sh -c go-wrapper download' returned a non-zero code: 1```

And -full
```
# cd .; git clone https://github.com/mitchellh/gox /go/src/github.com/mitchellh/gox
Cloning into '/go/src/github.com/mitchellh/gox'...
fatal: unable to access 'https://github.com/mitchellh/gox/': SSL certificate problem: unable to get local issuer certificate
package github.com/mitchellh/gox: exit status 128
The command '/bin/sh -c go get github.com/mitchellh/gox' returned a non-zero code: 1
```

**Comment by seenickcode** [comment]
@danports, were you able to find a solution to this?

**Comment by danports** [comment]
It looks like the build pipeline has changed since I opened this issue, since there are no public Packer builds listed on Docker Hub now. I'm guessing they're just `docker push`ing new images to the Hub now from a private CI system, so this issue is probably obsolete.
