### ISSUE TITLE
Image based on Debian

### ISSUE THREAD

**Issue by edahlseng** [hashicorp/docker-hub-images#70]
The Terraform docker images are very helpful, but lack many tools that are helpful in a CI context. Providing an official Terraform image based on Debian would fill this void!

**Comment by paultyng** [comment]
We no longer build Terraform docker images from this repository (Packer images are built here still).

Issues and pull requests on the Terraform docker image should be opened on the main Terraform repository: https://github.com/hashicorp/terraform

**Comment by edahlseng** [comment]
Thanks for the clarification @paultyng!
