### ISSUE TITLE
Use Go 1.11.4

### ISSUE THREAD

**Issue by mastertinner** [hashicorp/docker-hub-images#71]
The current `terraform:full` image is based on `golang:1.11.3`. This contains a nasty bug (https://github.com/golang/go/issues/29278). Please upgrade to using `golang1.11.4` (should be a matter of just rebuilding because the `golang` base image has been updated to 1.11.4 already.

**Comment by paultyng** [comment]
We no longer build Terraform docker images from this repository (Packer images are built here still).

Issues and pull requests on the Terraform docker image should be opened on the main Terraform repository: https://github.com/hashicorp/terraform
