### ISSUE TITLE
Packer 1.4.0 image

### ISSUE THREAD

**Issue by JorritSalverda** [hashicorp/docker-hub-images#75]
With Packer version 1.4.0 being available for 2 days can the Docker hub image get an update? Perhaps automate this to get released at the same time as the Github release is created?

**Comment by jonesbusy** [comment]
Same, would be nice to have the docker hub image updated, specially for CI systems that rely on containers for their build tools. 

Thanks in advance

**Comment by nigimaster** [comment]
Yes, please update the docker hub image asap, thank you!

**Comment by jonesbusy** [comment]
It's available, thanks a lot!
