### ISSUE TITLE
Request: less granular version tags

### ISSUE THREAD

**Issue by ouroboros8** [hashicorp/docker-hub-images#84]
I would like to be able to pull images with commands like:
```
docker pull hashicorp/terraform:0.12
```
and have it pull the latest patch for terraform 0.12. This could be acheived with moving 0.11/0.12 tags which point at the latest release for that version (e.g. 0.11 == 0.11.14).

**Comment by acondrat** [comment]
Would be great to have this!

**Comment by jrottenberg** [comment]
Especially on light and full variants :

- hashicorp/terraform:0.12-full
- hashicorp/terraform:0.12-light

**Comment by SwampDragons** [comment]
This has been implemented for the Packer images which are still generated by this repo; I believe terraform images now live in https://github.com/hashicorp/terraform/blob/master/Dockerfile

**Comment by jrottenberg** [comment]
Maybe the issue was not clear enough : the goal is to have images on dockerhub with tags matching MAJOR.MINOR , today we only have MAJOR.MINOR.PATCH versions : https://hub.docker.com/r/hashicorp/terraform/tags , 0.12.25 being the latest, but there is no rolling 0.12 tag that we can use in CI for example.


```
$ docker pull hashicorp/terraform:0.12
Error response from daemon: manifest for hashicorp/terraform:0.12 not found: manifest unknown: manifest unknown
```

Could you re-open it ?

**Comment by SwampDragons** [comment]
Those images are not maintained in this repo.

**Comment by jrottenberg** [comment]
oh sorry, yes, got hit by https://github.com/hashicorp/docker-hub-images/pull/74#issuecomment-486637114
https://github.com/hashicorp/terraform/issues/23224#issuecomment-547517627

ok.

But it doesn't seem to be https://github.com/hashicorp/terraform/blob/master/Dockerfile either : 


```
 docker history hashicorp/terraform:0.12.25 --no-trunc
IMAGE                                                                     CREATED             CREATED BY                                                                                                        SIZE                COMMENT
sha256:6f079c[...]        7 days ago          /bin/sh -c #(nop)  ENTRYPOINT ["/bin/terraform"]                                                                  0B
<missing>                 7 days ago          /bin/sh -c #(nop) COPY file:5cd98d92[...] in /bin/terraform    52.6MB
<missing>                 7 days ago          /bin/sh -c apk add --no-cache git openssh                                                                         22MB
<missing>                 7 days ago          /bin/sh -c #(nop)  LABEL com.hashicorp.terraform.version=                                                         0B
<missing>                 3 weeks ago         /bin/sh -c #(nop)  CMD ["/bin/sh"]                                                                                0B
<missing>                 3 weeks ago         /bin/sh -c #(nop) ADD file:b91adb67b6[...] in /                  5.61MB
```

But yeah I'll continue the conversation on https://github.com/hashicorp/terraform/issues/20669

Thank you for closing that one !

**Comment by jrottenberg** [comment]
found it  : https://github.com/hashicorp/terraform/blob/master/scripts/docker-release/Dockerfile-release
