### ISSUE TITLE
Add an image based on nightly

### ISSUE THREAD

**Issue by WebSpider** [hashicorp/docker-hub-images#90]
Hi! 

Can an image based on the 'nightly' tag be added?

https://github.com/hashicorp/packer/releases/tag/nightly

**Comment by SwampDragons** [comment]
This is a good idea -- I'm not sure when I'll have a chance to implement but I'll put it on our list of things to consider as we update our CI. I'm going to close this as a duplicate of #34 since it's asking for essentially the same thing.
