### ISSUE TITLE
Root user prevents image to be used without interaction

### ISSUE THREAD

**Issue by kandrejevs2** [hashicorp/docker-hub-images#94]
For local development we are using localstack and terraform to manage resources.
This image creates state file as root user, therefore to delete state and apply resources to fresh localstack container, statefile has to be deleted with `sudo rm` or permissions has to be changed with sudo.

**Comment by SwampDragons** [comment]
Hi, the Terraform image isn't maintained on this repo anymore. I have had the terraform remove this repo from the docker hub repository to reduce confusion; the correct place to open an issue is the terraform repo itself: https://github.com/hashicorp/terraform/
