### ISSUE TITLE
Installing openjdk11 failing on latest image (image released on Jun 24, 2020)

### ISSUE THREAD

**Issue by MBali-GitHub** [hashicorp/docker-hub-images#95]
When pulling the latest image, we are seeing a failure in installing openjdk11. It works fine with previous image.

**With hashicorp/terraform:latest**
 Step 20/29 : RUN apk add --no-cache openjdk11
  fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
 fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
 ERROR: unsatisfiable constraints:
   openjdk11 (missing):
     required by: world[openjdk11]
 The command '/bin/sh -c apk add --no-cache openjdk11' returned a non-zero code: 1

**With hashicorp/terraform:0.12.26**
Step 22/31 : RUN apk add --no-cache openjdk11
 fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
 fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
 (1/27) Installing openjdk11-jmods (11.0.5_p10-r0)
 (2/27) Installing openjdk11-demos (11.0.5_p10-r0)
 (3/27) Installing openjdk11-doc (11.0.5_p10-r0)
 (4/27) Installing java-common (0.2-r0)

**Comment by phinze** [comment]
Hi there - thank you for reporting this. You can find a detailed explanation of the root cause for this issue as well as some recommendations to avoid running into it in the future over at https://github.com/hashicorp/terraform/issues/25397#issuecomment-652656295.
